config/routes.rb
Rails.application.routes.draw do
  
root to: 'users#sign_in'

resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'validUser'
  end
end

resources :roles
resources :gadgets do
  member do
    get 'generatereport'
    post 'sendmail'
  end
end

resources :gadgets

resources :users_admin do
  collection do
    get 'sign_out'
  end
end

end

app/controllers/users_admin_controller.rb
class UsersAdminController < ApplicationController
	protect_from_forgery

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		
	end

	def create
		@new = User.new
		@new.first_name = params[:user][:first_name]
		@new.last_name = params[:user][:last_name]
		@new.institution = params[:user][:institution]
		@new.email = params[:user][:email]
		@new.password = params[:user][:password]
		
		if @new.save
			redirect_to users_admin_index_path
		else
			render 'new'
		end
	end

	def new
		
	end

	def edit
		@user = User.find(params[:id])
	end

	def update

		@user = User.find(params[:id])

		@user.first_name = params[:user][:first_name]
		@user.last_name = params[:user][:last_name]
		@user.institution = params[:user][:institution]
		@user.email = params[:user][:email]
		@user.password = params[:user][:password]
		@user.role = params[:user][:role]
		
		if @user.save
			redirect_to users_admin_index_path
		else
			render 'edit'
			#flash[:notice] = "You are signed up successfully"
		end
	end

	def signin
		
	end

	def contact
		
	end
	
	def sign_out
		
	end

	def destroy
			User.find(params[:id]).destroy
    	redirect_to users_admin_index_path
	end

end

app/views/users_admin/_form.html.erb
<%= form_for :user, url: @url, method: @method do |user|%>
  <div style="margin:0;padding:0;display:inline">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input name="authenticity_token" type="hidden" value="B1TuNwFttqwyi00Yz/h3t746UZXcJIeDlasaf2pnE4o=" />
  </div>
        
    <h1>User Registration Form</h1>
    <legend>
      <h4>To get access to this inventory list of gadgets please fill out the following form. Thank you </h4>
    </legend>
        
    <div class="form-group row">
      <%= user.label :FirstName, class: "string optional control-label control-label col-md-2 col-lg-2" %>
        <div class="col-md-4 col-lg-4">
              <%= user.text_field :first_name, class: "form-control" %>
        </div>
    </div>

    <div class="form-group row">
          <%= user.label :LastName, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.text_field :last_name, class: "form-control" %>
            </div>
    </div>

    <div class="form-group row">
          <%= user.label :Institution, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.text_field :institution, class: "form-control" %>
            </div>
    </div>

    <div class="form-group row">
          <%= user.label :Email, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.text_field :email, class: "form-control" %>
            </div>
    </div>
        
    <div class="form-group row">
          <%= user.label :Password, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.password_field :password, class: "form-control" %>
            </div>
    </div>

    <div class="form-group row">
          <%= user.label :Confirmation, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.password_field :confirmation, class: "form-control" %>
            </div>
    </div>

    <% @roles = Role.all%>
    <div class="form-group row">
      <%= user.label :Role, class: "string optional control-label control-label col-md-2 col-lg-2" %>
        <div class="col-md-4 col-lg-4">
           <select class="form-control" name="user[role_name]">
            <%= @roles.each do |r|%>
               <option value="<%= r.role_name%>"><%= r.role_name%></option>
            <% end %>
           </select>
        </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-8">
       <%= user.submit "Save", class: "btn btn-primary", style: "margin-left: 7%"%>
       <%= link_to 'Back', users_admin_index_path, :method => 'get', :class => "btn btn-default"%>
      </div>
    </div>
<% end %> 

app/views/users_admin/contact.html.erb
  <div class="container-fluid">
    <div class="row">

        <div class="col-md-10">
            <div class="row">
  <div class="col-md-9">
    <div class="well">
  <div class="row well form-style">
    <h4>If you want to contact us please fill out the form below we get back to you as soon as possible. </h4>
    <h4>Thank you</h4>
  <div class="col-md-6">
   
  <div style="margin:0;padding:0;display:inline">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <input name="authenticity_token" type="hidden" value="FVVqASyLBGLnMLPiJoYTVOgcdust65tXz++bKPDsWYo=" />
    </div>
                           
    <label class="string required control-label" for="contact_name"><abbr title="required">*</abbr> Name</label>
    <input class="form-control" id="name" name="contact[name]" size="61" type="text" />
                    
    <label class="email required control-label" for="contact_email"><abbr title="required">*</abbr> Email</label>
    <input class="form-control" id="email" name="contact[email]" required="required" size="61" type="email" value="" />
                            
    <label class="text required control-label" for="contact_message"><abbr title="required">*</abbr> Message</label>
    <textarea class="form-control" cols="40" id="text" name="contact[message]" rows="10" type="text">
    </textarea>
                              
    <input class="btn btn-primary btn-style " name="commit" type="submit" value="Send" />
    <button class="btn btn-default btn-style"><a href="/">Cancel</a></button>
  </form>  
</div>
</div>

app/views/users_admin/edit.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-lg-10 ">
      <% @url = {controller: 'users_admin', action: 'update', id: @user.id} %>
      <% @method = 'put'%>
      <%= notice %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users_admin/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-9" id="padding">
          <div class="row">
            <div class="col-md-10">
              <p class="lead"> Listing users </p>
            </div>
            
            <div class="col-md-2">
              <%= link_to 'Add User', new_users_admin_path,:class => 'btn btn-primary' %>
            </div>
          </div>

          <table class="table table-striped table-hover">
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Institution</th>
              <th>Role</th>
              <th colspan="3" class="text-center"></th>
            </tr>
        
                <% if @users.blank? %> 
                  <p> No Users </p>
                <% else %>
                <% @users.each do |allusers| %>
                  <tr>
                    <td><%= allusers.first_name%></td>
                    <td><%= allusers.last_name%></td>
                    <td><%= allusers.email%></td>
                    <td><%= allusers.institution%></td>
                    <td><%= allusers.role%></td>

        <td><%= link_to 'show',users_admin_path(allusers.id)%></td>
        <td><%= link_to 'edit', edit_users_admin_path(allusers.id) %></td>
        <td><%= link_to 'Destroy', users_admin_path(allusers.id), :method => 'delete' %>
        </td>
                  </tr>
                <% end %>
                <% end %>
          </table>
          <div  class='col-lg-offset-3'>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users_admin/new.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-lg-10 ">
      <% @url = {controller: 'users_admin', action: 'create', method: :post} %>
      <%= notice %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users_admin/show.html.erb
<div class="container-fluid">
<div class="row">
<div class="col-md-10">
<div class="row">
<div class="col-md-9">
    <p> 
      <b>Name:</b> 
      <%= @user.last_name %>
    </p>

    <p> 
      <b>Email:</b>
      <%= @user.email %>
    </p>

    <p> 
      <b>Institution:</b>
      <%= @user.institution %>
    </p>

    <p> 
      <b>Role:</b>
      <%= @user.role %>
    </p>

    <%= link_to 'Edit', edit_users_admin_path, :class => "btn btn-success", style: "margin-left: 0%"%>
    <%= link_to 'Back', users_admin_index_path, :class => 'btn btn-default' %>  
  </div>
</div>
</div>
</div>
</div>