config/routes.rb
Rails.application.routes.draw do
  
root to: 'users#sign_in'

resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'validUser'
  end
end

resources :roles
resources :gadgets do
  member do
    get 'generatereport'
    post 'sendmail'
  end
end

resources :gadgets

resources :users_admin do
  collection do
    get 'sign_out'
  end
end

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
	attr_accessible :title, :method_or_gadget,:useful_for,:analysis_group,
	:gadget_description,:cost,:company_name,:company_description,:company_website,
	:technology_used,:scientific_description,:CurrencyID,:field_1_explanation,
	:field_2_useful_for_which,:field_2_explanation,:name,:comment,
	:type_of_method_or_gadget,:evaluation_by_nrc,:evaluation_by_evaluator,:gadgetwebsite,
	:brochure,:tooltousers
	
	attr_accessible :type_of_method_or_gadget
	attr_accessor :email, :typeofmethod, :qualifyareasofinterest
	
	has_and_belongs_to_many :analysysgroups
	has_and_belongs_to_many :typeofmethods
	has_and_belongs_to_many :qualifyareasofinterests
	
	belongs_to :currency
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  protect_from_forgery
  
  def index
      @gadgets = Gadget.all
  end
  
  def new
    @gadget = Gadget.new
  end

  def create
    @gadget = Gadget.new(title: params[:gadget][:title],
    method_or_gadget: params[:gadget][:method_or_gadget],
    useful_for: params[:gadget][:useful_for],
    analysis_group: params[:gadget][:analysis_group], 
    gadget_description: params[:gadget][:gadget_description], 
    cost: params[:gadget][:cost], 
    company_name: params[:gadget][:company_name], 
    company_description: params[:gadget][:company_description], 
    company_website: params[:gadget][:company_website], 
    technology_used: params[:gadget][:technology_used], 
    scientific_description: params[:gadget][:scientific_description], field_1_explanation: params[:gadget][:field_1_explanation], field_2_useful_for_which: params[:gadget][:field_2_useful_for_which], field_2_explanation: params[:gadget][:field_2_explanation], name: params[:gadget][:name], comment: params[:gadget][:comment])
    
    analysys_array = params[:gadget][:analysis_group]
      if !analysys_array.nil?   
        analysys_array.each do |group| 
          @gadget.analysysgroups <<  
            Analysysgroup.find(group.to_i)
        end
      end

    type_of_method_array = params[:gadget][:type_of_method_or_gadget]
      if !type_of_method_array.nil?   
        type_of_method_array.each do |group| 
          @gadget.typeofmethods <<  Typeofmethod.find(group.to_i)
        end
      end

    qualifyareas_of_interest_array = params[:gadget][:qualifyareasofinterest]
      if !qualifyareas_of_interest_array.nil?   
        qualifyareas_of_interest_array.each do |group| 
          @gadget.qualifyareasofinterests <<  Qualifyareasofinterest.find(group.to_i)
        end
      end

    if @gadget.save
      flash[:notice] =  'Gadget successfully created.' 
      redirect_to gadgets_path
    else
      flash[:error] =  'Problem creating Gadget.' 
      render 'new'
    end
  end

  def edit
    @gadget = Gadget.find(params[:id])
      if !@gadget.nil?
        render 'edit'
      else
        render 'index'
      end
  end

  def update
    @gadget = Gadget.find(params[:id])
    @gadget.title = params[:gadget][:title]
    @gadget.company_name = params[:gadget][:company_name]
    @gadget.method_or_gadget = params[:gadget][:method_or_gadget]
    @gadget.useful_for = params[:gadget][:useful_for]
    @gadget.gadget_description = params[:gadget][:gadget_description]
    @gadget.cost = params[:gadget][:cost]
    @gadget.company_description = params[:gadget][:company_description]
    @gadget.company_website = params[:gadget][:company_website]
    
    if @gadget.save
      redirect_to gadgets_path
    else
      render 'edit'
    end
  end

  def show
    @show_gadget = Gadget.find(params[:id])
  end

  def destroy
    Gadget.find(params[:id]).destroy
    # render 'gadgets_path'
    redirect_to gadgets_path
  end

  def generatereport
    @gadget_report = Gadget.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "file_name", 
          :layout => 'pdflayout.html',
          :template => 'gadgets/generatereport.html.erb',
          :orientation => 'Portrait'
        end
      end
  end
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/_form.html.erb
<%= form_for :gadget, url: @url, method: @method do |f|%>     
<div class="container">
  <div class="col-lg-10">
    
    <div class="row">
      <div class="form-group">      
        <div class="col-md-9">
          <%= f.text_field :title, required: true, class: 'form-control input-md', placeholder: 'Enter Title Here' %>
        </div>
        
        <div class="col-md-3"> 
          <%= link_to "Back", gadgets_path, class: 'btn btn-primary' %>
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      </div>
    </div><hr/>
      
    <div class="col-lg-8">
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Name of the method/gadget</label>  
            <div class="col-md-7">
              <%= f.text_field :method_or_gadget, required: true, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">What is it for?</label>  
            <div class="col-md-7">
              <%= f.text_field :useful_for, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
      <div class="form-group">
      <label class="col-md-4 control-label">Analysis group(s)</label>
        <div class="col-md-7" style="padding-top:13px">
              
          <% Analysysgroup.all.each do |a_value| %> 
            <% if @gadget.new_record? %>
              <%= f.check_box(:analysis_group, { :multiple => true }, a_value.id, nil) %>
              <%=  a_value.name %>  
            <% else %>
                  
              <% if @gadget.analysis_group.pluck(:id).include?(a_value.id)  %>
                <%= f.check_box(:analysis_group, { :multiple => true, checked:  true}, a_value.id, nil) %>
                <%=  a_value.name %>  
                  
              <% else %>
                <%= f.check_box(:analysis_group, { :multiple => true }, a_value.id, nil) %>
                <%=  a_value.name %>  
              <% end %> 
            <% end %>
          <% end %>
        </div>
      </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Type of method/gadget</label>
            <div class="col-md-7" style="padding-top:13px">
              <% Typeofmethod.all.each do |a_value| %> 
                <% if @gadget.new_record? %>
                  <%= f.check_box(:type_of_method_or_gadget, { :multiple => true }, a_value.id, nil) %>
                  <%=  a_value.name %>  
                <% else %>
                  <% if @gadget.typeofmethods.pluck(:id).include?(a_value.id)   %>
                    <%= f.check_box(:type_of_method_or_gadget, { :multiple => true, checked:  true}, a_value.id, nil) %>
                    <%=  a_value.name %>  
                  <% else %>
                    <%= f.check_box(:type_of_method_or_gadget, { :multiple => true }, a_value.id, nil) %>
                        <%=  a_value.name %>  
                  <% end %> 
                <% end %>
              <% end %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="">Gadget Description</label>
            <div class="col-md-7"> 
              <%= f.text_area :gadget_description, class: 'form-control', rows: 4 %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="buttondropdown">Cost</label>
            <div class="col-md-5">
              <%= f.text_field :cost, class: 'form-control' %>
            </div>

            <div class="col-md-3">
              <%= f.select :CurrencyID, Currency.all.collect {|p| [ p.name, p.id] },{:default => 'Guest'}, {:class => 'form-control', id: 'currency_select'} %>
            </div>  
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="radios">Is the tool available to users?</label>
            <div class="col-md-8"> 
              <label class="radio-inline" for="radios-0">
                <%= f.radio_button :tooltousers, "Yes" %>
              Yes
              </label> 
              <label class="radio-inline" for="radios-1">
                <%= f.radio_button :tooltousers, "No" %>
                No
              </label> 
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="">Gadget website</label>
          <div class="col-md-7"> 
            <%= f.text_field :gadgetwebsite, class: 'form-control'%>
          </div>
        </div>
      </div>
      <br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="">Brochure</label>
          <div class="col-md-7"> 
            <%= f.text_field :brochure, class: 'form-control'%>
          </div>
        </div>
      </div>
      <br><hr/>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Company name</label>  
            <div class="col-md-7">
              <%= f.text_field :company_name, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Company description</label>  
            <div class="col-md-7">
              <%= f.text_area :company_description, class: 'form-control input-md', rows:4 %>
            </div>
        </div>
      </div><br>
        
      <div class="row">     
        <div class="form-group">
          <label class="col-md-4 control-label">Company website</label>  
            <div class="col-md-7">
              <%= f.text_field :company_website, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Technology used</label>  
            <div class="col-md-7">
              <%= f.text_field :technology_used, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Scientific description of</label>  
            <div class="col-md-7">
              <%= f.text_area :scientific_description, class: 'form-control input-md', rows: 4 %>
            </div>
        </div>
      </div><br>


      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">QuaLiFY area of interest</label>
            <div class="col-md-7" style="padding-top:13px">
              <% Qualifyareasofinterest.all.each do |a_value| %> 
                <% if @gadget.new_record? %>
                  <%= f.check_box(:qualifyareasofinterest, { :multiple => true }, a_value.id, nil) %>
                  <%=  a_value.name %>  
                  <% else %>
                    <% if @qi.qualifyareasofinterests.pluck(:id).include?(a_value.id)   %>
                      <%= f.check_box(:qualifyareasofinterest, { :multiple => true, checked:  true}, a_value.id, nil) %>
                      <%=  a_value.name %>  
                    <% else %>
                      <%= f.check_box(:qualifyareasofinterest, { :multiple => true }, a_value.id, nil) %>
                      <%=  a_value.name %>  
                  <% end %> 
                <% end %>
              <% end %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Explanation by evaluator(NRC)</label>
            <div class="col-md-7"> 
              <%= f.text_area :field_2_explanation, class: 'form-control input-md', rows: 4 %>
            </div>
        </div>
      </div><br><hr/>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Name of evaluator(NRC)</label>  
            <div class="col-md-7">
              <%= f.text_field :name, class: 'form-control input-md',
                   id: 'fieldwidth' %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Comments/suggestion of evaluator</label>  
            <div class="col-md-7">
              <%= f.text_area :comment, class: 'form-control input-md', rows: 4, id: 'fieldwidth' %>
            </div>
        </div>  
      </div><br>

     <div class="text-center"> 
        <%= link_to "Back", gadgets_path, class: 'btn btn-primary' %>
        <%= f.submit "Save", class: 'btn btn-primary' %>
      </div>
    </div>
  </div> 
</div>
  <!-- insert code for avatars here -->
  <!-- insert code for video location here -->
<% end %>

app/views/gadgets/edit.html.erb
<div class="container">
    <div class="row"> 
      <div class="col-lg-10 ">              
        <% @url = {controller: 'gadgets', action: 'update', id: @gadget.id} %>
        <% @method = 'put'%>
        <%= notice %>
        <%= render 'form' %>
      </div>
    </div>   
</div> 

app/views/gadgets/index.html.erb
<div class="row">
  <div class="col-md-10" id="padding">
    <div class="col-md-10">
      <p class="lead"> Gadget Inventory</p> 
      <div class="row">
        </br>
      </div>
    </div>

    <div class="col-md-2">
      <%= link_to 'ADD GADGET', new_gadget_path, class: 'btn btn-primary' %>
    </div>

    <% if !@gadgets.empty? %>
    <table class="table table-striped table-hover">
          <tr>
            <th>Title</th>
            <th>Name of the Tool</th>
            <th>Analysis Group(s)</th>
            <th>Company name</th>
            <th colspan="3" class="text-center"></th>
          </tr>
             <% @gadgets.each do |gadget| %>
          <tr>
            <td><%= gadget.title %></td>
            <td><%= gadget.method_or_gadget %></td>
            <td><% gadget.analysysgroups.each do |group| %>
                <% if group == gadget.analysysgroups.last %>
                    <%= group.name%>
                <% else%>
                    <%= group.name+","%>
                <% end %>
              <% end %>
            </td>

            <td>
              <%= gadget.company_name%>
            </td>
            
            <td><%= link_to 'Show', gadget_path(gadget.id) %></td>
            <td><%= link_to 'Edit', edit_gadget_path(gadget.id) %></td>
            <td><%= link_to 'Delete',gadget_path(gadget.id), method: :delete, data: { confirm: 'Are you sure?' }%></td>
          </tr>
    <% end %>
    </table>
    <% else %>
      <div class="col-md-10">
        <p class="text-center"> There are no matched records.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/gadgets/new.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-lg-10 ">              
      <% @url = {controller: 'gadgets', action: 'create', method: :post} %>
      <%= notice %>
      <%= render 'form' %>
    </div>
  </div>   
</div>

app/views/gadgets/show.html.erb
<div class="row">
  <div class="form-group">
    <div class="col-md-5">
      Gadget
    </div>
  
    <div class="col-md-7">
      <%= link_to 'Back', gadgets_path,:class => 'btn btn-primary' %> 
      <%= link_to 'Edit', edit_gadget_path,:class => "btn btn-primary"%>
      <%= link_to "Pdf", generatereport_gadget_path(@show_gadget.id, format: :pdf), class: 'btn btn-primary' %>

      <!-- <a href="/qualityinventory/9/generatereport.pdf" class="btn btn-primary">Pdf</a> -->

      <button class="btn btn-primary" data-toggle="modal" data-target ="#myModal">Send mail 
      </button>
    </div>
  </div>
</div> 
<hr/>

<div class="row">
  <div class="col-md-8">
    <dl>
      <dt>Name of the method/gadget</dt>
      <dd><%= @show_gadget.method_or_gadget%></dd>
    </dl>

    <dl>
      <dt>What is it for?</dt>
      <dd><%= @show_gadget.useful_for%></dd>
    </dl>
            
    <dl>
      <% if !@show_gadget.analysysgroups.empty? %>
        <dt>Analysis group(s)</dt>
      <% @show_gadget.analysysgroups.each do |group| %>
        <dd> <%= group.name %></dd>
          <% end %>
          <% end %>
    </dl>


    <dl>
      <dt>Type of method/gadget</dt>
      <% if !@show_gadget.typeofmethods.empty?%>
        
          <% @show_gadget.typeofmethods.each do |group| %>
            <dd> <%= group.name %></dd>
          <% end %>
      <% end %>

    <dl>
      <dt>Gadget description</dt>
      <dd><%= @show_gadget.gadget_description %></dd>
    </dl>
            
    <dl>
        <% if !@show_gadget.cost.nil?%>
          <dt>Cost</dt>
          <dd> <%= @show_gadget.cost %>&nbsp<%= @show_gadget.currency.name if !@show_gadget.currency.nil? %></dd>
        <% end %>
    </dl>

    <dl>
      <dt>Is the tool avaliable to users?</dt>
      <% !if @show_gadget.tooltousers.nil?%>
        <dd> 
          <% if @show_gadget.tooltousers == "Yes" %> 

                      Yes
          <% else %>
          <% if @show_gadget.tooltousers == "No" %>
                      No
          <% end %>
          <% end %>
        </dd>
      <% end %>
    </dl>

    <dl>
      <% if !@show_gadget.gadgetwebsite.blank?%>
        <dt>Gadget website</dt>
          <dd> <%= @show_gadget.gadgetwebsite %></dd>
            <% end %>
    </dl>

    <dl>
      <% if !@show_gadget.brochure.blank?%>
        <dt>Brochure</dt>
          <dd> <%= @show_gadget.brochure %></dd>
      <% end %>

      <dt>Cost</dt>
      <dd><%= @show_gadget.cost %></dd>
    </dl>
  </div>
          
  <div class="col-md-4">
    <div class="row">
      <img alt="" data-target=".bs-example-modal-lg" data-toggle="modal" src="/system/qualityinventories/avatars/000/000/009/medium/004_Adidas_micoach.jpg?1397049350" />
    </div>
    
    <div class="row">
      <iframe style="margin-top:6px;" width="177" height="160" src="//www.youtube.com/embed/REqqkL_00-4" frameborder="0" allowfullscreen>show video</iframe>
    </div>
  </div>
</div><hr/>

  <dl>
    <dt>Company name</dt>
    <dd> <%= @show_gadget.company_name%></dd>
  </dl>
        
  <dl>
    <dt>Company description</dt>
    <dd><%= @show_gadget.company_description%></dd>
  </dl>
        
  <dl>
    <dt>Company website</dt>
    <dd> <%= @show_gadget.company_website%></dd>
  </dl>

  <dl>
    <% if !@show_gadget.qualifyareasofinterests.empty? %>
      <dt>QuaLiFY area of interest</dt>
        <% @show_gadget.qualifyareasofinterests.each do |group| %>
          <dd> <%= group.name %></dd>
        <% end %>
  </dl>
    <% end %><hr/>
    
  <dl>
    <dt>Evaluated by NRC </dt>
    <dd><%if  @show_gadget.evaluation_by_nrc %>
              Yes
        <% else %>
              No
        <% end %>
    </dd>
  </dl>

  <dl>
    <dt>Name of evaluator </dt>
      <dd></dd>
      <dd> <%= @show_gadget.company_description%></dd>
  </dl>

  <dl>
    <dt>Evaluated by NRC </dt>
      <dd> </dd>
  </dl>
        
  <dl>
    <dt>Usefulness for which field lab? </dt>
    <dd> </dd>
  </dl>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Mail Gadget Inventory</h4>
      </div>
      <div class="modal-body">
        <%= form_for @show_gadget, url: {controller: 'gadgets', action: 'sendmail', id: @show_gadget.id}, method: :post, :html => {class:'form-horizontal' }  do |f| %>

        <%= f.email_field :email, required: true, class: 'form-control', placeholder: 'Enter email address'  %>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Send mail", class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>