config/routes.rb
Rails.application.routes.draw do
  
root to: 'users#sign_in'

resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'validUser'
  end
end

resources :roles
resources :gadgets do
  member do
    get 'generatereport'
    post 'sendmail'
  end
end

resources :gadgets

resources :users_admin do
  collection do
    get 'sign_out'
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="nav navbar-header">
      <a href="/admins/contact" class="navbar-brand">Contact</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">English <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">German</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li>
        <%= link_to 'New Member Registration', sign_up_users_path, :method => 'get'%>
        </li>
        <li><a href="/users/sign_in">LOGIN</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav> <br>

app/views/application/_sidebar.html.erb
<div class="sidebar-padding">
	<div class="list-group">
    <%= link_to 'Users', users_admin_index_path, :method =>
        	'get', :class => "list-group-item active"%>
    <%= link_to 'Roles', roles_path, :method =>
        	'get', :class => "list-group-item active"%>
    <%= link_to 'Gadgets Inventory', gadgets_path, :method =>'get', :class => "list-group-item"%>
  </div>
</div>